// <auto-generated>
// This file is generated by SceneIdGenerator.
// DO NOT EDIT MANUALLY.
// </auto-generated>

using System;
using Lighthouse.Scene;

namespace DungeonInn.LighthouseGenerated
{
    public static class DungeonInnModuleSceneId
    {
        public static readonly ModuleSceneId None = new ModuleSceneId(1, string.Empty);
        public static readonly ModuleSceneId ScreenStack = new ModuleSceneId(2, "ScreenStack");
        public static readonly ModuleSceneId WorldRenderModule = new ModuleSceneId(3, "WorldRenderModule");
        public static readonly ModuleSceneId UIModule = new ModuleSceneId(4, "UIModule");
        public static readonly ModuleSceneId CameraModule = new ModuleSceneId(5, "CameraModule");

        public static ReadOnlySpan<ModuleSceneId> All
        {
            get
            {
                return new ModuleSceneId[]
                {
                    None,
                    ScreenStack,
                    WorldRenderModule,
                    UIModule,
                    CameraModule,
                };
            }
        }
    }
}
