//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.19.0
//     from Assets/DungeonInn/Runtime/StaticResources/InputActions/InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace DungeonInn.Input
{
    /// <summary>
    /// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/DungeonInn/Runtime/StaticResources/InputActions/InputActions.inputactions".
    /// </summary>
    /// <remarks>
    /// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
    /// </remarks>
    /// <example>
    /// <code>
    /// using namespace UnityEngine;
    /// using UnityEngine.InputSystem;
    ///
    /// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
    /// public class Example : MonoBehaviour, MyActions.IPlayerActions
    /// {
    ///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
    ///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
    ///
    ///     void Awake()
    ///     {
    ///         m_Actions = new MyActions_Actions();              // Create asset object.
    ///         m_Player = m_Actions.Player;                      // Extract action map object.
    ///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
    ///     }
    ///
    ///     void OnDestroy()
    ///     {
    ///         m_Actions.Dispose();                              // Destroy asset object.
    ///     }
    ///
    ///     void OnEnable()
    ///     {
    ///         m_Player.Enable();                                // Enable all actions within map.
    ///     }
    ///
    ///     void OnDisable()
    ///     {
    ///         m_Player.Disable();                               // Disable all actions within map.
    ///     }
    ///
    ///     #region Interface implementation of MyActions.IPlayerActions
    ///
    ///     // Invoked when "Move" action is either started, performed or canceled.
    ///     public void OnMove(InputAction.CallbackContext context)
    ///     {
    ///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
    ///     }
    ///
    ///     // Invoked when "Attack" action is either started, performed or canceled.
    ///     public void OnAttack(InputAction.CallbackContext context)
    ///     {
    ///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
    ///     }
    ///
    ///     #endregion
    /// }
    /// </code>
    /// </example>
    public partial class @InputActions: IInputActionCollection2, IDisposable
    {
        /// <summary>
        /// Provides access to the underlying asset instance.
        /// </summary>
        public InputActionAsset asset { get; }

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public @InputActions()
        {
            asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""InputActions"",
    ""maps"": [
        {
            ""name"": ""Global"",
            ""id"": ""00000000-0000-0000-0001-000000000001"",
            ""actions"": [],
            ""bindings"": []
        },
        {
            ""name"": ""Scene"",
            ""id"": ""00000000-0000-0000-0001-000000000002"",
            ""actions"": [
                {
                    ""name"": ""Back"",
                    ""type"": ""Button"",
                    ""id"": ""00000000-0000-0000-0002-000000000001"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cancel"",
                    ""type"": ""Button"",
                    ""id"": ""00000000-0000-0000-0002-000000000002"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TogglePause"",
                    ""type"": ""Button"",
                    ""id"": ""00000000-0000-0000-0002-000000000003"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShowInnStatus"",
                    ""type"": ""Button"",
                    ""id"": ""00000000-0000-0000-0002-000000000004"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WorldCameraMove"",
                    ""type"": ""Value"",
                    ""id"": ""00000000-0000-0000-0002-000000000005"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""WorldCameraLook"",
                    ""type"": ""Value"",
                    ""id"": ""00000000-0000-0000-0002-000000000006"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""WorldCameraRotate"",
                    ""type"": ""Button"",
                    ""id"": ""00000000-0000-0000-0002-000000000007"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WorldCameraZoom"",
                    ""type"": ""Value"",
                    ""id"": ""00000000-0000-0000-0002-000000000008"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PreviousWorldLayer"",
                    ""type"": ""Button"",
                    ""id"": ""00000000-0000-0000-0002-000000000009"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NextWorldLayer"",
                    ""type"": ""Button"",
                    ""id"": ""00000000-0000-0000-0002-000000000010"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WorldActorClick"",
                    ""type"": ""Button"",
                    ""id"": ""00000000-0000-0000-0002-000000000011"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WorldActorSelectNext"",
                    ""type"": ""Button"",
                    ""id"": ""00000000-0000-0000-0002-000000000012"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WorldActorSelectPrevious"",
                    ""type"": ""Button"",
                    ""id"": ""00000000-0000-0000-0002-000000000013"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""00000000-0000-0000-0002-000000000101"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""00000000-0000-0000-0002-000000000102"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""00000000-0000-0000-0002-000000000103"",
                    ""path"": ""<Keyboard>/backspace"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""00000000-0000-0000-0002-000000000104"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TogglePause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""00000000-0000-0000-0002-000000000105"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShowInnStatus"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2DVector"",
                    ""id"": ""00000000-0000-0000-0002-000000000106"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WorldCameraMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""00000000-0000-0000-0002-000000000107"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WorldCameraMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""00000000-0000-0000-0002-000000000108"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WorldCameraMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""00000000-0000-0000-0002-000000000109"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WorldCameraMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""00000000-0000-0000-0002-000000000110"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WorldCameraMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2DVector"",
                    ""id"": ""00000000-0000-0000-0002-000000000111"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WorldCameraMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""00000000-0000-0000-0002-000000000112"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WorldCameraMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""00000000-0000-0000-0002-000000000113"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WorldCameraMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""00000000-0000-0000-0002-000000000114"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WorldCameraMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""00000000-0000-0000-0002-000000000115"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WorldCameraMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""00000000-0000-0000-0002-000000000116"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WorldCameraLook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""00000000-0000-0000-0002-000000000117"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WorldCameraRotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""00000000-0000-0000-0002-000000000118"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WorldCameraZoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""00000000-0000-0000-0002-000000000119"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PreviousWorldLayer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""00000000-0000-0000-0002-000000000120"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextWorldLayer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""00000000-0000-0000-0002-000000000121"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WorldActorClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""00000000-0000-0000-0002-000000000122"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WorldActorSelectNext"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""00000000-0000-0000-0002-000000000123"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WorldActorSelectNext"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""00000000-0000-0000-0002-000000000124"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WorldActorSelectPrevious"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""00000000-0000-0000-0002-000000000125"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WorldActorSelectPrevious"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""ScreenStack"",
            ""id"": ""00000000-0000-0000-0001-000000000003"",
            ""actions"": [
                {
                    ""name"": ""Back"",
                    ""type"": ""Button"",
                    ""id"": ""00000000-0000-0000-0003-000000000001"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cancel"",
                    ""type"": ""Button"",
                    ""id"": ""00000000-0000-0000-0003-000000000002"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Confirm"",
                    ""type"": ""Button"",
                    ""id"": ""00000000-0000-0000-0003-000000000003"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""00000000-0000-0000-0003-000000000101"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""00000000-0000-0000-0003-000000000102"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""00000000-0000-0000-0003-000000000103"",
                    ""path"": ""<Keyboard>/backspace"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""00000000-0000-0000-0003-000000000104"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Confirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""00000000-0000-0000-0003-000000000105"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Confirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""00000000-0000-0000-0003-000000000106"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Confirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // Global
            m_Global = asset.FindActionMap("Global", throwIfNotFound: true);
            // Scene
            m_Scene = asset.FindActionMap("Scene", throwIfNotFound: true);
            m_Scene_Back = m_Scene.FindAction("Back", throwIfNotFound: true);
            m_Scene_Cancel = m_Scene.FindAction("Cancel", throwIfNotFound: true);
            m_Scene_TogglePause = m_Scene.FindAction("TogglePause", throwIfNotFound: true);
            m_Scene_ShowInnStatus = m_Scene.FindAction("ShowInnStatus", throwIfNotFound: true);
            m_Scene_WorldCameraMove = m_Scene.FindAction("WorldCameraMove", throwIfNotFound: true);
            m_Scene_WorldCameraLook = m_Scene.FindAction("WorldCameraLook", throwIfNotFound: true);
            m_Scene_WorldCameraRotate = m_Scene.FindAction("WorldCameraRotate", throwIfNotFound: true);
            m_Scene_WorldCameraZoom = m_Scene.FindAction("WorldCameraZoom", throwIfNotFound: true);
            m_Scene_PreviousWorldLayer = m_Scene.FindAction("PreviousWorldLayer", throwIfNotFound: true);
            m_Scene_NextWorldLayer = m_Scene.FindAction("NextWorldLayer", throwIfNotFound: true);
            m_Scene_WorldActorClick = m_Scene.FindAction("WorldActorClick", throwIfNotFound: true);
            m_Scene_WorldActorSelectNext = m_Scene.FindAction("WorldActorSelectNext", throwIfNotFound: true);
            m_Scene_WorldActorSelectPrevious = m_Scene.FindAction("WorldActorSelectPrevious", throwIfNotFound: true);
            // ScreenStack
            m_ScreenStack = asset.FindActionMap("ScreenStack", throwIfNotFound: true);
            m_ScreenStack_Back = m_ScreenStack.FindAction("Back", throwIfNotFound: true);
            m_ScreenStack_Cancel = m_ScreenStack.FindAction("Cancel", throwIfNotFound: true);
            m_ScreenStack_Confirm = m_ScreenStack.FindAction("Confirm", throwIfNotFound: true);
        }

        ~@InputActions()
        {
            UnityEngine.Debug.Assert(!m_Global.enabled, "This will cause a leak and performance issues, InputActions.Global.Disable() has not been called.");
            UnityEngine.Debug.Assert(!m_Scene.enabled, "This will cause a leak and performance issues, InputActions.Scene.Disable() has not been called.");
            UnityEngine.Debug.Assert(!m_ScreenStack.enabled, "This will cause a leak and performance issues, InputActions.ScreenStack.Disable() has not been called.");
        }

        /// <summary>
        /// Destroys this asset and all associated <see cref="InputAction"/> instances.
        /// </summary>
        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
        public void Enable()
        {
            asset.Enable();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
        public void Disable()
        {
            asset.Disable();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
        public IEnumerable<InputBinding> bindings => asset.bindings;

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Global
        private readonly InputActionMap m_Global;
        private List<IGlobalActions> m_GlobalActionsCallbackInterfaces = new List<IGlobalActions>();
        /// <summary>
        /// Provides access to input actions defined in input action map "Global".
        /// </summary>
        public struct GlobalActions
        {
            private @InputActions m_Wrapper;

            /// <summary>
            /// Construct a new instance of the input action map wrapper class.
            /// </summary>
            public GlobalActions(@InputActions wrapper) { m_Wrapper = wrapper; }
            /// <summary>
            /// Provides access to the underlying input action map instance.
            /// </summary>
            public InputActionMap Get() { return m_Wrapper.m_Global; }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
            public void Enable() { Get().Enable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
            public void Disable() { Get().Disable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
            public bool enabled => Get().enabled;
            /// <summary>
            /// Implicitly converts an <see ref="GlobalActions" /> to an <see ref="InputActionMap" /> instance.
            /// </summary>
            public static implicit operator InputActionMap(GlobalActions set) { return set.Get(); }
            /// <summary>
            /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <param name="instance">Callback instance.</param>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
            /// </remarks>
            /// <seealso cref="GlobalActions" />
            public void AddCallbacks(IGlobalActions instance)
            {
                if (instance == null || m_Wrapper.m_GlobalActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_GlobalActionsCallbackInterfaces.Add(instance);
            }

            /// <summary>
            /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <remarks>
            /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
            /// </remarks>
            /// <seealso cref="GlobalActions" />
            private void UnregisterCallbacks(IGlobalActions instance)
            {
            }

            /// <summary>
            /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="GlobalActions.UnregisterCallbacks(IGlobalActions)" />.
            /// </summary>
            /// <seealso cref="GlobalActions.UnregisterCallbacks(IGlobalActions)" />
            public void RemoveCallbacks(IGlobalActions instance)
            {
                if (m_Wrapper.m_GlobalActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            /// <summary>
            /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
            /// </summary>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
            /// </remarks>
            /// <seealso cref="GlobalActions.AddCallbacks(IGlobalActions)" />
            /// <seealso cref="GlobalActions.RemoveCallbacks(IGlobalActions)" />
            /// <seealso cref="GlobalActions.UnregisterCallbacks(IGlobalActions)" />
            public void SetCallbacks(IGlobalActions instance)
            {
                foreach (var item in m_Wrapper.m_GlobalActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_GlobalActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        /// <summary>
        /// Provides a new <see cref="GlobalActions" /> instance referencing this action map.
        /// </summary>
        public GlobalActions @Global => new GlobalActions(this);

        // Scene
        private readonly InputActionMap m_Scene;
        private List<ISceneActions> m_SceneActionsCallbackInterfaces = new List<ISceneActions>();
        private readonly InputAction m_Scene_Back;
        private readonly InputAction m_Scene_Cancel;
        private readonly InputAction m_Scene_TogglePause;
        private readonly InputAction m_Scene_ShowInnStatus;
        private readonly InputAction m_Scene_WorldCameraMove;
        private readonly InputAction m_Scene_WorldCameraLook;
        private readonly InputAction m_Scene_WorldCameraRotate;
        private readonly InputAction m_Scene_WorldCameraZoom;
        private readonly InputAction m_Scene_PreviousWorldLayer;
        private readonly InputAction m_Scene_NextWorldLayer;
        private readonly InputAction m_Scene_WorldActorClick;
        private readonly InputAction m_Scene_WorldActorSelectNext;
        private readonly InputAction m_Scene_WorldActorSelectPrevious;
        /// <summary>
        /// Provides access to input actions defined in input action map "Scene".
        /// </summary>
        public struct SceneActions
        {
            private @InputActions m_Wrapper;

            /// <summary>
            /// Construct a new instance of the input action map wrapper class.
            /// </summary>
            public SceneActions(@InputActions wrapper) { m_Wrapper = wrapper; }
            /// <summary>
            /// Provides access to the underlying input action "Scene/Back".
            /// </summary>
            public InputAction @Back => m_Wrapper.m_Scene_Back;
            /// <summary>
            /// Provides access to the underlying input action "Scene/Cancel".
            /// </summary>
            public InputAction @Cancel => m_Wrapper.m_Scene_Cancel;
            /// <summary>
            /// Provides access to the underlying input action "Scene/TogglePause".
            /// </summary>
            public InputAction @TogglePause => m_Wrapper.m_Scene_TogglePause;
            /// <summary>
            /// Provides access to the underlying input action "Scene/ShowInnStatus".
            /// </summary>
            public InputAction @ShowInnStatus => m_Wrapper.m_Scene_ShowInnStatus;
            /// <summary>
            /// Provides access to the underlying input action "Scene/WorldCameraMove".
            /// </summary>
            public InputAction @WorldCameraMove => m_Wrapper.m_Scene_WorldCameraMove;
            /// <summary>
            /// Provides access to the underlying input action "Scene/WorldCameraLook".
            /// </summary>
            public InputAction @WorldCameraLook => m_Wrapper.m_Scene_WorldCameraLook;
            /// <summary>
            /// Provides access to the underlying input action "Scene/WorldCameraRotate".
            /// </summary>
            public InputAction @WorldCameraRotate => m_Wrapper.m_Scene_WorldCameraRotate;
            /// <summary>
            /// Provides access to the underlying input action "Scene/WorldCameraZoom".
            /// </summary>
            public InputAction @WorldCameraZoom => m_Wrapper.m_Scene_WorldCameraZoom;
            /// <summary>
            /// Provides access to the underlying input action "Scene/PreviousWorldLayer".
            /// </summary>
            public InputAction @PreviousWorldLayer => m_Wrapper.m_Scene_PreviousWorldLayer;
            /// <summary>
            /// Provides access to the underlying input action "Scene/NextWorldLayer".
            /// </summary>
            public InputAction @NextWorldLayer => m_Wrapper.m_Scene_NextWorldLayer;
            /// <summary>
            /// Provides access to the underlying input action "Scene/WorldActorClick".
            /// </summary>
            public InputAction @WorldActorClick => m_Wrapper.m_Scene_WorldActorClick;
            /// <summary>
            /// Provides access to the underlying input action "Scene/WorldActorSelectNext".
            /// </summary>
            public InputAction @WorldActorSelectNext => m_Wrapper.m_Scene_WorldActorSelectNext;
            /// <summary>
            /// Provides access to the underlying input action "Scene/WorldActorSelectPrevious".
            /// </summary>
            public InputAction @WorldActorSelectPrevious => m_Wrapper.m_Scene_WorldActorSelectPrevious;
            /// <summary>
            /// Provides access to the underlying input action map instance.
            /// </summary>
            public InputActionMap Get() { return m_Wrapper.m_Scene; }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
            public void Enable() { Get().Enable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
            public void Disable() { Get().Disable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
            public bool enabled => Get().enabled;
            /// <summary>
            /// Implicitly converts an <see ref="SceneActions" /> to an <see ref="InputActionMap" /> instance.
            /// </summary>
            public static implicit operator InputActionMap(SceneActions set) { return set.Get(); }
            /// <summary>
            /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <param name="instance">Callback instance.</param>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
            /// </remarks>
            /// <seealso cref="SceneActions" />
            public void AddCallbacks(ISceneActions instance)
            {
                if (instance == null || m_Wrapper.m_SceneActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_SceneActionsCallbackInterfaces.Add(instance);
                @Back.started += instance.OnBack;
                @Back.performed += instance.OnBack;
                @Back.canceled += instance.OnBack;
                @Cancel.started += instance.OnCancel;
                @Cancel.performed += instance.OnCancel;
                @Cancel.canceled += instance.OnCancel;
                @TogglePause.started += instance.OnTogglePause;
                @TogglePause.performed += instance.OnTogglePause;
                @TogglePause.canceled += instance.OnTogglePause;
                @ShowInnStatus.started += instance.OnShowInnStatus;
                @ShowInnStatus.performed += instance.OnShowInnStatus;
                @ShowInnStatus.canceled += instance.OnShowInnStatus;
                @WorldCameraMove.started += instance.OnWorldCameraMove;
                @WorldCameraMove.performed += instance.OnWorldCameraMove;
                @WorldCameraMove.canceled += instance.OnWorldCameraMove;
                @WorldCameraLook.started += instance.OnWorldCameraLook;
                @WorldCameraLook.performed += instance.OnWorldCameraLook;
                @WorldCameraLook.canceled += instance.OnWorldCameraLook;
                @WorldCameraRotate.started += instance.OnWorldCameraRotate;
                @WorldCameraRotate.performed += instance.OnWorldCameraRotate;
                @WorldCameraRotate.canceled += instance.OnWorldCameraRotate;
                @WorldCameraZoom.started += instance.OnWorldCameraZoom;
                @WorldCameraZoom.performed += instance.OnWorldCameraZoom;
                @WorldCameraZoom.canceled += instance.OnWorldCameraZoom;
                @PreviousWorldLayer.started += instance.OnPreviousWorldLayer;
                @PreviousWorldLayer.performed += instance.OnPreviousWorldLayer;
                @PreviousWorldLayer.canceled += instance.OnPreviousWorldLayer;
                @NextWorldLayer.started += instance.OnNextWorldLayer;
                @NextWorldLayer.performed += instance.OnNextWorldLayer;
                @NextWorldLayer.canceled += instance.OnNextWorldLayer;
                @WorldActorClick.started += instance.OnWorldActorClick;
                @WorldActorClick.performed += instance.OnWorldActorClick;
                @WorldActorClick.canceled += instance.OnWorldActorClick;
                @WorldActorSelectNext.started += instance.OnWorldActorSelectNext;
                @WorldActorSelectNext.performed += instance.OnWorldActorSelectNext;
                @WorldActorSelectNext.canceled += instance.OnWorldActorSelectNext;
                @WorldActorSelectPrevious.started += instance.OnWorldActorSelectPrevious;
                @WorldActorSelectPrevious.performed += instance.OnWorldActorSelectPrevious;
                @WorldActorSelectPrevious.canceled += instance.OnWorldActorSelectPrevious;
            }

            /// <summary>
            /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <remarks>
            /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
            /// </remarks>
            /// <seealso cref="SceneActions" />
            private void UnregisterCallbacks(ISceneActions instance)
            {
                @Back.started -= instance.OnBack;
                @Back.performed -= instance.OnBack;
                @Back.canceled -= instance.OnBack;
                @Cancel.started -= instance.OnCancel;
                @Cancel.performed -= instance.OnCancel;
                @Cancel.canceled -= instance.OnCancel;
                @TogglePause.started -= instance.OnTogglePause;
                @TogglePause.performed -= instance.OnTogglePause;
                @TogglePause.canceled -= instance.OnTogglePause;
                @ShowInnStatus.started -= instance.OnShowInnStatus;
                @ShowInnStatus.performed -= instance.OnShowInnStatus;
                @ShowInnStatus.canceled -= instance.OnShowInnStatus;
                @WorldCameraMove.started -= instance.OnWorldCameraMove;
                @WorldCameraMove.performed -= instance.OnWorldCameraMove;
                @WorldCameraMove.canceled -= instance.OnWorldCameraMove;
                @WorldCameraLook.started -= instance.OnWorldCameraLook;
                @WorldCameraLook.performed -= instance.OnWorldCameraLook;
                @WorldCameraLook.canceled -= instance.OnWorldCameraLook;
                @WorldCameraRotate.started -= instance.OnWorldCameraRotate;
                @WorldCameraRotate.performed -= instance.OnWorldCameraRotate;
                @WorldCameraRotate.canceled -= instance.OnWorldCameraRotate;
                @WorldCameraZoom.started -= instance.OnWorldCameraZoom;
                @WorldCameraZoom.performed -= instance.OnWorldCameraZoom;
                @WorldCameraZoom.canceled -= instance.OnWorldCameraZoom;
                @PreviousWorldLayer.started -= instance.OnPreviousWorldLayer;
                @PreviousWorldLayer.performed -= instance.OnPreviousWorldLayer;
                @PreviousWorldLayer.canceled -= instance.OnPreviousWorldLayer;
                @NextWorldLayer.started -= instance.OnNextWorldLayer;
                @NextWorldLayer.performed -= instance.OnNextWorldLayer;
                @NextWorldLayer.canceled -= instance.OnNextWorldLayer;
                @WorldActorClick.started -= instance.OnWorldActorClick;
                @WorldActorClick.performed -= instance.OnWorldActorClick;
                @WorldActorClick.canceled -= instance.OnWorldActorClick;
                @WorldActorSelectNext.started -= instance.OnWorldActorSelectNext;
                @WorldActorSelectNext.performed -= instance.OnWorldActorSelectNext;
                @WorldActorSelectNext.canceled -= instance.OnWorldActorSelectNext;
                @WorldActorSelectPrevious.started -= instance.OnWorldActorSelectPrevious;
                @WorldActorSelectPrevious.performed -= instance.OnWorldActorSelectPrevious;
                @WorldActorSelectPrevious.canceled -= instance.OnWorldActorSelectPrevious;
            }

            /// <summary>
            /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="SceneActions.UnregisterCallbacks(ISceneActions)" />.
            /// </summary>
            /// <seealso cref="SceneActions.UnregisterCallbacks(ISceneActions)" />
            public void RemoveCallbacks(ISceneActions instance)
            {
                if (m_Wrapper.m_SceneActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            /// <summary>
            /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
            /// </summary>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
            /// </remarks>
            /// <seealso cref="SceneActions.AddCallbacks(ISceneActions)" />
            /// <seealso cref="SceneActions.RemoveCallbacks(ISceneActions)" />
            /// <seealso cref="SceneActions.UnregisterCallbacks(ISceneActions)" />
            public void SetCallbacks(ISceneActions instance)
            {
                foreach (var item in m_Wrapper.m_SceneActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_SceneActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        /// <summary>
        /// Provides a new <see cref="SceneActions" /> instance referencing this action map.
        /// </summary>
        public SceneActions @Scene => new SceneActions(this);

        // ScreenStack
        private readonly InputActionMap m_ScreenStack;
        private List<IScreenStackActions> m_ScreenStackActionsCallbackInterfaces = new List<IScreenStackActions>();
        private readonly InputAction m_ScreenStack_Back;
        private readonly InputAction m_ScreenStack_Cancel;
        private readonly InputAction m_ScreenStack_Confirm;
        /// <summary>
        /// Provides access to input actions defined in input action map "ScreenStack".
        /// </summary>
        public struct ScreenStackActions
        {
            private @InputActions m_Wrapper;

            /// <summary>
            /// Construct a new instance of the input action map wrapper class.
            /// </summary>
            public ScreenStackActions(@InputActions wrapper) { m_Wrapper = wrapper; }
            /// <summary>
            /// Provides access to the underlying input action "ScreenStack/Back".
            /// </summary>
            public InputAction @Back => m_Wrapper.m_ScreenStack_Back;
            /// <summary>
            /// Provides access to the underlying input action "ScreenStack/Cancel".
            /// </summary>
            public InputAction @Cancel => m_Wrapper.m_ScreenStack_Cancel;
            /// <summary>
            /// Provides access to the underlying input action "ScreenStack/Confirm".
            /// </summary>
            public InputAction @Confirm => m_Wrapper.m_ScreenStack_Confirm;
            /// <summary>
            /// Provides access to the underlying input action map instance.
            /// </summary>
            public InputActionMap Get() { return m_Wrapper.m_ScreenStack; }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
            public void Enable() { Get().Enable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
            public void Disable() { Get().Disable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
            public bool enabled => Get().enabled;
            /// <summary>
            /// Implicitly converts an <see ref="ScreenStackActions" /> to an <see ref="InputActionMap" /> instance.
            /// </summary>
            public static implicit operator InputActionMap(ScreenStackActions set) { return set.Get(); }
            /// <summary>
            /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <param name="instance">Callback instance.</param>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
            /// </remarks>
            /// <seealso cref="ScreenStackActions" />
            public void AddCallbacks(IScreenStackActions instance)
            {
                if (instance == null || m_Wrapper.m_ScreenStackActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_ScreenStackActionsCallbackInterfaces.Add(instance);
                @Back.started += instance.OnBack;
                @Back.performed += instance.OnBack;
                @Back.canceled += instance.OnBack;
                @Cancel.started += instance.OnCancel;
                @Cancel.performed += instance.OnCancel;
                @Cancel.canceled += instance.OnCancel;
                @Confirm.started += instance.OnConfirm;
                @Confirm.performed += instance.OnConfirm;
                @Confirm.canceled += instance.OnConfirm;
            }

            /// <summary>
            /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <remarks>
            /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
            /// </remarks>
            /// <seealso cref="ScreenStackActions" />
            private void UnregisterCallbacks(IScreenStackActions instance)
            {
                @Back.started -= instance.OnBack;
                @Back.performed -= instance.OnBack;
                @Back.canceled -= instance.OnBack;
                @Cancel.started -= instance.OnCancel;
                @Cancel.performed -= instance.OnCancel;
                @Cancel.canceled -= instance.OnCancel;
                @Confirm.started -= instance.OnConfirm;
                @Confirm.performed -= instance.OnConfirm;
                @Confirm.canceled -= instance.OnConfirm;
            }

            /// <summary>
            /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="ScreenStackActions.UnregisterCallbacks(IScreenStackActions)" />.
            /// </summary>
            /// <seealso cref="ScreenStackActions.UnregisterCallbacks(IScreenStackActions)" />
            public void RemoveCallbacks(IScreenStackActions instance)
            {
                if (m_Wrapper.m_ScreenStackActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            /// <summary>
            /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
            /// </summary>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
            /// </remarks>
            /// <seealso cref="ScreenStackActions.AddCallbacks(IScreenStackActions)" />
            /// <seealso cref="ScreenStackActions.RemoveCallbacks(IScreenStackActions)" />
            /// <seealso cref="ScreenStackActions.UnregisterCallbacks(IScreenStackActions)" />
            public void SetCallbacks(IScreenStackActions instance)
            {
                foreach (var item in m_Wrapper.m_ScreenStackActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_ScreenStackActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        /// <summary>
        /// Provides a new <see cref="ScreenStackActions" /> instance referencing this action map.
        /// </summary>
        public ScreenStackActions @ScreenStack => new ScreenStackActions(this);
        /// <summary>
        /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Global" which allows adding and removing callbacks.
        /// </summary>
        /// <seealso cref="GlobalActions.AddCallbacks(IGlobalActions)" />
        /// <seealso cref="GlobalActions.RemoveCallbacks(IGlobalActions)" />
        public interface IGlobalActions
        {
        }
        /// <summary>
        /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Scene" which allows adding and removing callbacks.
        /// </summary>
        /// <seealso cref="SceneActions.AddCallbacks(ISceneActions)" />
        /// <seealso cref="SceneActions.RemoveCallbacks(ISceneActions)" />
        public interface ISceneActions
        {
            /// <summary>
            /// Method invoked when associated input action "Back" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnBack(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Cancel" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnCancel(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "TogglePause" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnTogglePause(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "ShowInnStatus" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnShowInnStatus(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "WorldCameraMove" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnWorldCameraMove(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "WorldCameraLook" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnWorldCameraLook(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "WorldCameraRotate" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnWorldCameraRotate(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "WorldCameraZoom" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnWorldCameraZoom(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "PreviousWorldLayer" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnPreviousWorldLayer(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "NextWorldLayer" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnNextWorldLayer(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "WorldActorClick" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnWorldActorClick(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "WorldActorSelectNext" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnWorldActorSelectNext(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "WorldActorSelectPrevious" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnWorldActorSelectPrevious(InputAction.CallbackContext context);
        }
        /// <summary>
        /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "ScreenStack" which allows adding and removing callbacks.
        /// </summary>
        /// <seealso cref="ScreenStackActions.AddCallbacks(IScreenStackActions)" />
        /// <seealso cref="ScreenStackActions.RemoveCallbacks(IScreenStackActions)" />
        public interface IScreenStackActions
        {
            /// <summary>
            /// Method invoked when associated input action "Back" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnBack(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Cancel" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnCancel(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Confirm" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnConfirm(InputAction.CallbackContext context);
        }
    }
}
